### ISSUE TITLE
List the image services

### ISSUE THREAD

**Issue by raphaelfournier** [polifonia-project/facets-search-engine#1]
The docker image should have some services, available through a REST API. 
Ideas from today's meeting: 
- send a score (MEI), index it
- query an index with a pattern

A few questions needs to be addressed (to be completed):
- index creation, should it be explicit? implicit? both? (imho: explicit or both, with also an index deletion possibility)

This needs to be specified in the doc (on Overleaf).

**Comment by TiangeZhu** [comment]
Document is now available on overleaf. 
TODO: change format and upload the final version to this repo.
