### ISSUE TITLE
home UI: protect our data 

### ISSUE THREAD

**Issue by TiangeZhu** [polifonia-project/facets-search-engine#118]
protect scorelib index to not be deleted, right now we hard-code it in the code. In the future, this will be related to #76

**Comment by TiangeZhu** [comment]
tried to hard code this in rest/views.py but it does not work because ES directly process commands like "curl -X DELETE http://localhost:9200/index_name/"

**Comment by raphaelfournier** [comment]
It should be hard coded in the GUI at least. Few people will be able to run a curl query, they will need to be careful/not malicious.

**Comment by TiangeZhu** [comment]
it's possible to hide the neuma repo by changing settings in settings.py. it is impossible to unable a curl command directly to ES for deleting the index.
