### ISSUE TITLE
Facets ordering

### ISSUE THREAD

**Issue by raphaelfournier** [polifonia-project/facets-search-engine#156]
Facets should be ordered in a "user-friendly" way. At the moment, "num of measures" gives (top -> bottom): 132-261-165-200-105-87… 
Integers should be ordered (ascending), words with lexical order ("unknown" sometimes appear very high).

Also: if nothing is present, the facet may be not displayed.
Also: better spacing (less scrolling)

**Comment by TiangeZhu** [comment]
fixed the " if nothing is present, the facet may be not displayed."

**Comment by TiangeZhu** [comment]
fixed display in alphabetical order
