### ISSUE TITLE
Procedure to index a document

### ISSUE THREAD

**Issue by raphaelfournier** [polifonia-project/facets-search-engine#7]
As the title says, there should be a REST call to index a document. 
A few parameters needs to be taken (name/id of the document, of the index). To be discussed below if necessary.

**Comment by TiangeZhu** [comment]
Works after commit babe8392ac7274bd163a5893fc3f040878b0b11c. 
For example, run command:
curl -X PUT -H "Content-type: application/mei" http://localhost:8000/index/lklk/ -d @data/friuli001.mei 
Then chromatic, diatonic, rhythmic and notes features would be extracted from the file "friuli001.mei" for indexing, and you may find a document named "lklk" under a ES index named "index" with all these information.
